#!/usr/bin/env python3
"""Regenerate the Kaggle kernels that run the four models §35 could not
finish measuring on the VPS.

    python3 tool/kaggle/build_spectro_kernel.py
    cd tool/kaggle/spectro-eval && python -m kaggle kernels push -p .
    cd ../cometbeat-full && python -m kaggle kernels push -p .

Same rule as `build_kernel.py`, for the same reason: **a Kaggle script kernel
uploads only its `code_file`** (kaggle-usage.md gotcha #3), so a kernel has to
be one self-contained file. Rather than maintain a second copy of any
evaluation, each kernel is generated by concatenating a Kaggle preamble with
the local evaluators, verbatim, and everything a worker needs that is not in
the script arrives via `dataset_sources`.

Three kernels come out of here.

* **spectro-eval** (Python) reproduces §35.3's MusicNet note-level table on a
  machine that is not shared, and answers the two questions §35 left open
  about cost: native-ORT throughput at 1/2/4 intra-op threads, and peak RSS,
  for all four models. The accuracy half is a genuine second opinion — the
  decoders are `tool/spectro_notes.py`'s numpy ports and the metric is
  `mir_eval` itself, where §35.3 used `lib/hft.dart` / `lib/oaf.dart` and
  `lib/note_metrics.dart`.
* **cometbeat-guitar** and **cometbeat-cello** (Dart) run CometBeat's own
  RMVPE and FCPE engines, in CometBeat's own runtime, over the FULL corpora.
  §35.6 could report RMVPE on GuitarSet not at all (one 22-second file
  reached 3.5 GB in `onnx_runtime_dart` and was OOM-killed) and FCPE on 40 of
  180 files; a Kaggle worker has the memory the VPS did not. **Nothing is
  chunked.** Chunking RMVPE's input would make it a different engine from the
  one CometBeat ships, which is exactly why §35.6 declined to do it.

The corpora are fetched from Zenodo inside each kernel. None of them is
mirrored as a Kaggle dataset: CLAUDE.md's licence note is that these corpora
are for local evaluation and must never be redistributed.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BENCH = os.path.dirname(os.path.dirname(HERE))
TOOL = os.path.join(BENCH, "tool")

# The Kaggle account that owns the private model dataset. Private datasets are
# per-account (gotcha #13): the dataset and the kernel must be the same
# account, or the attachment silently fails as "not valid dataset sources".
ACCOUNT = "chr1s4"
MODEL_DATASET = f"{ACCOUNT}/crisptuner-onnx"
DART_VERSION = "3.13.4"
# Pin the branch the Dart kernels clone. `git push` does NOT update a Kaggle
# kernel and a kernel that clones `main` would silently score a different
# tree from the one under review (gotcha #24), so the ref is explicit and the
# kernel prints the SHA it actually got.
REPO = "https://github.com/CrispStrobe/flutter_tuner.git"
REPO_REF = "bench/kaggle-four-models"


def strip_module(path, drop_from=None, rename_main=None):
    """One local tool's source, ready to be concatenated with another.

    Everything above the first `import` is the module docstring, which is
    kept — it is where the reasoning lives and a kernel log is a bad place to
    lose it. `if __name__ == "__main__"` is dropped because the kernel has
    one entry point, and `main` is renamed because two evaluators in one file
    would otherwise shadow each other. That renaming is the only edit made to
    any evaluator on the way to Kaggle.
    """
    src = open(path).read()
    if drop_from and drop_from in src:
        src = src[:src.index(drop_from)]
    src = src.split('if __name__ == "__main__":')[0]
    if rename_main:
        src = src.replace("\ndef main():", f"\ndef {rename_main}():")
    return src.rstrip() + "\n"


# ---------------------------------------------------------------------------
# spectro-eval: Python, native ORT, MusicNet + the four-model timing table
# ---------------------------------------------------------------------------

SPECTRO_PREAMBLE = '''#!/usr/bin/env python3
"""CrispTuner: the four models §35 could not finish measuring, on Kaggle.

Generated from bench/tool/{spectro_reference,spectro_notes,onnx_timing}.py by
bench/tool/kaggle/build_spectro_kernel.py — do not edit here; the local
copies are the ones that get reviewed.

Two jobs, on a worker that is not shared with anyone:

1. **Reproduce §35.3.** hFT-Transformer and Onsets & Frames over MusicNet's
   ten-piece test split, native ORT, with the decoders re-implemented in
   numpy and the metric taken from `mir_eval` itself. §35.3's numbers came
   through `lib/hft.dart`, `lib/oaf.dart` and `lib/note_metrics.dart`; if the
   two agree, neither port has drifted, and if they disagree the difference
   is below the model rather than in it.

2. **Cost, properly measured.** Native-ORT wall time as a multiple of real
   time at 1, 2 and 4 intra-op threads, and peak RSS, for all four models —
   one process per (model, thread count), so the memory figure belongs to a
   model rather than to a run.

MusicNet is Zenodo 5120004. **Its label times are sample indices at 44100 Hz,
not seconds**, which has already cost this project one wrong table; the
constant is named in `spectro_notes.py` rather than inlined. The archive is
one 11 GB tarball of which the test split is ~205 MB, so it is streamed and
the stream is abandoned once the twenty members needed are out.
"""

import os
import subprocess
import sys
import tarfile
import urllib.request

WORK = "/kaggle/working"
DATA = os.path.join(WORK, "datasets", "musicnet")
MUSICNET = "https://zenodo.org/records/5120004/files/musicnet.tar.gz?download=1"

# `onnx_timing` runs one child process per (model, thread count) by
# re-executing this same file with `--only`. The child must not re-run the
# install or the download, and this is the flag that says so.
CHILD = "--only" in sys.argv


def models_dir():
    """Where `dataset_sources` mounted the ONNX bundle.

    Kaggle has used two layouts for this; both are checked rather than
    guessed at, because the failure mode of guessing is a kernel that runs
    for ten minutes and then cannot find a model.
    """
    for p in ("/kaggle/input/crisptuner-onnx",
              "/kaggle/input/datasets/{account}/crisptuner-onnx"):
        if os.path.isdir(p):
            return p
    raise SystemExit("crisptuner-onnx is not attached; see gotcha #13 — a "
                     "private dataset can only be used by kernels pushed "
                     "from the account that owns it")


def sh(cmd):
    print(f"$ {cmd}", flush=True)
    subprocess.run(cmd, shell=True, check=True)


def require_internet():
    """Fail loudly and early rather than hanging.

    Kaggle CPU workers get no internet even with `enable_internet: "true"`,
    and a GPU worker can lose it too. The corpus needs it and there is no
    degraded mode worth attempting.
    """
    try:
        urllib.request.urlopen("https://zenodo.org", timeout=30).close()
    except Exception as exc:  # noqa: BLE001 - any failure means the same thing
        raise SystemExit(f"no internet on this worker ({exc}); re-run")


def install():
    sh(f"{sys.executable} -m pip install -q mir_eval librosa soundfile "
       f"onnxruntime")


def fetch_musicnet():
    """The test split only: 10 wavs and 10 label CSVs out of an 11 GB tar.

    `tarfile` in stream mode cannot seek, so the archive is read in order and
    dropped on the floor member by member until the twenty wanted are out —
    at which point the stream is abandoned. How much of the 11 GB that costs
    depends on where the members sit, and the kernel prints it rather than
    claiming a figure.
    """
    want_audio = os.path.join(DATA, "musicnet", "test_data")
    want_labels = os.path.join(DATA, "musicnet", "test_labels")
    if os.path.isdir(want_audio) and len(os.listdir(want_audio)) >= 10:
        return
    os.makedirs(DATA, exist_ok=True)
    print("streaming MusicNet (11 GB tar, keeping the ~205 MB test split)",
          flush=True)
    got = 0
    seen = 0
    with urllib.request.urlopen(MUSICNET) as r:
        with tarfile.open(fileobj=r, mode="r|gz") as t:
            for m in t:
                seen += 1
                if not m.isfile():
                    continue
                if ("/test_data/" in m.name and m.name.endswith(".wav")) or \\
                   ("/test_labels/" in m.name and m.name.endswith(".csv")):
                    t.extract(m, DATA)
                    got += 1
                    print(f"  {m.name} ({m.size / 1e6:.1f} MB)", flush=True)
                    if got >= 20:
                        break
    print(f"extracted {got} members after reading {seen} tar entries",
          flush=True)
    print(f"audio: {len(os.listdir(want_audio))}, "
          f"labels: {len(os.listdir(want_labels))}", flush=True)


if not CHILD:
    require_internet()
    install()
    fetch_musicnet()

# Everything below is bench/tool/spectro_reference.py, spectro_notes.py and
# onnx_timing.py, verbatim but for the renamed entry points.
# ---------------------------------------------------------------------------

'''

SPECTRO_DRIVER = '''

# ---------------------------------------------------------------------------
# The kernel's own entry point.
# ---------------------------------------------------------------------------

MODELS = models_dir()

if CHILD:
    # A timing child: one model, one thread count, its own address space.
    sys.exit(main_timing())

print("\\n=== MusicNet test split, hFT and O&F, mir_eval ===\\n", flush=True)
sys.argv = [
    "spectro_notes",
    "--data", DATA,
    "--models", MODELS,
    "--threads", "2",
    "--sweep",
    "--out", os.path.join(WORK, "spectro_notes.json"),
]
main_notes()

print("\\n=== native ORT cost: four models, 1/2/4 threads, peak RSS ===\\n",
      flush=True)
sys.argv = [
    "onnx_timing",
    "--wav", os.path.join(DATA, "musicnet", "test_data", "2191.wav"),
    "--seconds", "30",
    "--threads", "1,2,4",
    "--models", MODELS,
    "--cometbeat", MODELS,
    "--out", os.path.join(WORK, "onnx_timing.json"),
]
main_timing()
'''


def build_spectro():
    target = os.path.join(HERE, "spectro-eval")
    os.makedirs(target, exist_ok=True)
    body = "".join([
        SPECTRO_PREAMBLE.replace("{account}", ACCOUNT),
        strip_module(os.path.join(TOOL, "spectro_reference.py"),
                     drop_from="\ndef main():"),
        "\n\n",
        strip_module(os.path.join(TOOL, "spectro_notes.py"),
                     rename_main="main_notes"),
        "\n\n",
        strip_module(os.path.join(TOOL, "onnx_timing.py"),
                     rename_main="main_timing"),
        SPECTRO_DRIVER,
    ])
    # The evaluators import each other by module name when run locally; in
    # one concatenated file those imports would fail, and dropping them is
    # safe precisely because the imported names are defined above.
    body = body.replace(
        "from spectro_reference import mel, resample, sigmoid\n",
        "# (spectro_reference is inlined above)\n")
    body = body.replace("    from spectro_reference import mel\n", "")
    body = body.replace("    from spectro_reference import resample\n", "")
    with open(os.path.join(target, "spectro_eval.py"), "w") as f:
        f.write(body)
    meta = {
        "id": f"{ACCOUNT}/crisptuner-spectro-eval",
        "title": "CrispTuner spectro eval",
        "code_file": "spectro_eval.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "competition_sources": [],
        "dataset_sources": [MODEL_DATASET],
        "kernel_sources": [],
        "model_sources": [],
    }
    with open(os.path.join(target, "kernel-metadata.json"), "w") as f:
        json.dump(meta, f, indent=1)
    print("wrote", target)


# ---------------------------------------------------------------------------
# cometbeat-*: Dart, CometBeat's own engines, the FULL corpora
# ---------------------------------------------------------------------------

COMETBEAT = '''#!/usr/bin/env python3
"""CometBeat's RMVPE and FCPE over the FULL corpora, in CometBeat's runtime.

Generated by bench/tool/kaggle/build_spectro_kernel.py — do not edit here.

§35.6 reported these two engines on prefixes and said so: FCPE on 40 of
GuitarSet's 180 solo files, RMVPE on 55 of MUSERC's 109 cello takes, and
RMVPE on GuitarSet not at all, because one 22-second file reached 3.5 GB of
resident memory in `onnx_runtime_dart` and was killed. A Kaggle worker has
memory the shared VPS did not.

Two rules this kernel does not break.

* **Nothing is chunked.** RMVPE's U-Net takes the whole recording as one
  forward pass; splitting it would make this a different engine from the one
  CometBeat ships, and measuring a different engine was the thing §35.6
  declined to do.
* **Nothing is re-implemented.** The engines are CometBeat's own Dart files
  as `tool/sync_cometbeat.sh` copies them, run by `bin/cometbeat.dart`
  through `onnx_runtime_dart` — the same runtime, the same decode, the same
  scoring code as every other row in this report. The only thing Kaggle
  changes is the machine.

`--subset N` accumulates a second table over the first N files of the SAME
pass, so §35.6's prefix and the full corpus can be compared line for line
without the confound of two different runs. That is the question §35.6 had to
leave open when it warned that `cb-pyin` moves 82.63 -> 80.45 between them.
"""

import os
import subprocess
import sys
import urllib.request
import zipfile

WORK = "/kaggle/working"
DATA = os.path.join(WORK, "datasets")
DART = os.path.join(WORK, "dart-sdk", "bin", "dart")
DART_URL = ("https://storage.googleapis.com/dart-archive/channels/stable/"
            "release/{dart_version}/sdk/dartsdk-linux-x64-release.zip")
REPO = "{repo}"
REF = "{ref}"
CORPUS = "{corpus}"
ENGINES = "{engines}"
SUBSET = "{subset}"


def sh(cmd, **kw):
    print(f"$ {{cmd}}", flush=True)
    subprocess.run(cmd, shell=True, check=True, **kw)


def require_internet():
    try:
        urllib.request.urlopen("https://zenodo.org", timeout=30).close()
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(f"no internet on this worker ({{exc}}); re-run")


def models_dir():
    for p in ("/kaggle/input/crisptuner-onnx",
              "/kaggle/input/datasets/{account}/crisptuner-onnx"):
        if os.path.isdir(p):
            return p
    raise SystemExit("crisptuner-onnx is not attached (gotcha #13)")


def install_dart():
    if os.path.exists(DART):
        return
    zip_path = os.path.join(WORK, "dart.zip")
    urllib.request.urlretrieve(DART_URL, zip_path)
    with zipfile.ZipFile(zip_path) as z:
        z.extractall(WORK)
    os.chmod(DART, 0o755)
    for extra in ("dartaotruntime", "utils/gen_snapshot"):
        p = os.path.join(WORK, "dart-sdk", "bin", extra)
        if os.path.exists(p):
            os.chmod(p, 0o755)
    os.remove(zip_path)
    sh(f"{{DART}} --version")


def clone():
    """The repo at an explicit ref, with the SHA printed.

    `git push` does not update a Kaggle kernel (gotcha #24), so a kernel and
    the tree it tests can drift apart with nothing in the log looking wrong.
    Printing both the ref asked for and the SHA obtained is what makes that
    visible.
    """
    dst = os.path.join(WORK, "flutter_tuner")
    if not os.path.isdir(dst):
        sh(f"git clone --depth 1 --branch {{REF}} {{REPO}} {{dst}}")
    sha = subprocess.run(["git", "-C", dst, "rev-parse", "HEAD"],
                         capture_output=True, text=True).stdout.strip()
    print(f"cloned {{REF}} at {{sha}}", flush=True)
    return dst


def fetch_guitarset():
    """GuitarSet (Zenodo 3371780, CC BY 4.0): annotations + mono-mic audio."""
    audio, ann = os.path.join(DATA, "audio"), os.path.join(DATA, "annotation")
    if os.path.isdir(audio) and len(os.listdir(audio)) > 100:
        return
    os.makedirs(DATA, exist_ok=True)
    for name, url in [
        ("annotation.zip",
         "https://zenodo.org/records/3371780/files/annotation.zip?download=1"),
        ("audio_mono-mic.zip",
         "https://zenodo.org/records/3371780/files/audio_mono-mic.zip?download=1"),
    ]:
        target = os.path.join(DATA, name)
        print(f"fetching {{name}}", flush=True)
        urllib.request.urlretrieve(url, target)
        out = ann if "annotation" in name else audio
        os.makedirs(out, exist_ok=True)
        with zipfile.ZipFile(target) as z:
            z.extractall(out)
        os.remove(target)
    print(f"audio {{len(os.listdir(audio))}}, annotations {{len(os.listdir(ann))}}",
          flush=True)


def fetch_muserc():
    """MUSERC (Zenodo 1560651, CC BY 4.0). Only `SA/` — 72 MB of the 1.4 GB."""
    sa = os.path.join(DATA, "muserc", "MUSERC", "SA")
    if os.path.isdir(sa) and len(os.listdir(sa)) > 100:
        return
    root = os.path.join(DATA, "muserc")
    os.makedirs(root, exist_ok=True)
    target = os.path.join(root, "MUSERC.zip")
    print("fetching MUSERC (1.4 GB)", flush=True)
    urllib.request.urlretrieve(
        "https://zenodo.org/records/1560651/files/MUSERC.zip?download=1", target)
    with zipfile.ZipFile(target) as z:
        for name in z.namelist():
            if name.startswith("MUSERC/SA/") and not name.startswith("__MACOSX"):
                z.extract(name, root)
    os.remove(target)
    print(f"takes: {{len(os.listdir(sa))}}", flush=True)


require_internet()
install_dart()
repo = clone()
models = models_dir()
if CORPUS == "guitar":
    fetch_guitarset()
else:
    fetch_muserc()

bench = os.path.join(repo, "bench")
sh(f"{{DART}} pub get", cwd=bench)
print(f"\\nfree memory before the run:", flush=True)
sh("free -g || true")

# `--models` is the mounted dataset: rmvpe.onnx, fcpe.onnx and the two mel
# assets sit flat in it, which is the layout `loadNeural` expects.
cmd = (f"{{DART}} run bin/cometbeat.dart --corpus {{CORPUS}} --data {{DATA}} "
       f"--models {{models}} --engines {{ENGINES}} --subset {{SUBSET}}")
# Not check=True: an OOM kill part-way through is a RESULT here, not a
# harness failure, and the per-file progress lines say exactly how far the
# run got. Swallowing the exit code would be wrong; hiding the log would be
# worse.
print(f"$ {{cmd}}", flush=True)
rc = subprocess.run(cmd, shell=True, cwd=bench).returncode
print(f"\\ncometbeat.dart exited {{rc}}", flush=True)
sh("free -g || true")
if rc != 0:
    print("NON-ZERO EXIT: if this is 137 the kernel OOM-killed it, and the "
          "last progress line above is the file it died on.", flush=True)
'''


def build_cometbeat(name, corpus, engines, subset, title):
    target = os.path.join(HERE, name)
    os.makedirs(target, exist_ok=True)
    src = COMETBEAT.format(
        dart_version=DART_VERSION, repo=REPO, ref=REPO_REF, corpus=corpus,
        engines=engines, subset=subset, account=ACCOUNT)
    with open(os.path.join(target, "cometbeat_eval.py"), "w") as f:
        f.write(src)
    meta = {
        "id": f"{ACCOUNT}/{name}",
        "title": title,
        "code_file": "cometbeat_eval.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "competition_sources": [],
        "dataset_sources": [MODEL_DATASET],
        "kernel_sources": [],
        "model_sources": [],
    }
    with open(os.path.join(target, "kernel-metadata.json"), "w") as f:
        json.dump(meta, f, indent=1)
    print("wrote", target)


def main():
    build_spectro()
    # One engine per GuitarSet kernel. RMVPE is the expensive and the
    # fragile one — ~2.4x real time and the thing that OOM-killed the VPS —
    # so pairing it with FCPE would risk losing both to one kill.
    build_cometbeat("crisptuner-cometbeat-rmvpe-guitar", "guitar",
                    "cb-rmvpe", 40, "CrispTuner CometBeat RMVPE GuitarSet")
    build_cometbeat("crisptuner-cometbeat-fcpe-guitar", "guitar",
                    "cb-fcpe", 40, "CrispTuner CometBeat FCPE GuitarSet")
    build_cometbeat("crisptuner-cometbeat-cello", "cello",
                    "cb-rmvpe,cb-fcpe", 55, "CrispTuner CometBeat cello")


if __name__ == "__main__":
    main()
